# Jekyll configuration

name: Middle Earth
name_en: J.R.R. Tolkien, Christopher Tolkien

# url is currently only used for the RSS feed in feed.xml
url: https://junesirius.github.io
baseurl: "/MiddleEarth"

## default date_format
date_format: 
  title: "%m-%d-%Y"
  archive: "%m-%d"
  categories: "%m-%d-%Y"
  tags: "%m-%d-%Y"

# Language
lan: "cn" 

paginate: 1000 # tmp

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak", "assets/images/**/*"]

permalink: /:title